FROM ollama/ollama:latest

# Pré-baixa o modelo de embeddings
#RUN ollama pull embedding-gemma

# Porta padrão do Ollama
EXPOSE 11434

# Inicializa o servidor Ollama
#CMD ["ollama", "serve"]

CMD ["serve"]